### ISSUE TITLE
`fetchPriority` warning when running docs

### ISSUE THREAD

**Issue by kawaijoe** [forus-labs/forui#148]
This warning appears when running the documentation.

```
Warning: React does not recognize the `fetchPriority` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `fetchpriority` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at img
    at eval (webpack-internal:///./node_modules/.pnpm/next@13.5.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/client/image-component.js:131:11)
    at eval (webpack-internal:///./node_modules/.pnpm/next@13.5.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/client/image-component.js:238:47)
    at Logo (webpack-internal:///./components/logo.tsx:16:17)
    at a
    at LinkComponent (webpack-internal:///./node_modules/.pnpm/next@13.5.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/client/link.js:105:19)
    at eval (webpack-internal:///./node_modules/.pnpm/nextra-theme-docs@2.13.4_next@13.5.6_react-dom@18.3.1_react@18.3.1__react@18.3.1__nextra@2.13_k2lwaadcjqvucsrfzrlpwgtlbq/node_modules/nextra-theme-docs/dist/index.js:318:18)
    at nav
    at div
    at Navbar (webpack-internal:///./node_modules/.pnpm/nextra-theme-docs@2.13.4_next@13.5.6_react-dom@18.3.1_react@18.3.1__react@18.3.1__nextra@2.13_k2lwaadcjqvucsrfzrlpwgtlbq/node_modules/nextra-theme-docs/dist/index.js:1499:19)
    at div
    at InnerLayout (webpack-internal:///./node_modules/.pnpm/nextra-theme-docs@2.13.4_next@13.5.6_react-dom@18.3.1_react@18.3.1__react@18.3.1__nextra@2.13_k2lwaadcjqvucsrfzrlpwgtlbq/node_modules/nextra-theme-docs/dist/index.js:2965:3)
    at m (webpack-internal:///./node_modules/.pnpm/next-themes@0.2.1_next@13.5.6_react-dom@18.3.1_react@18.3.1__react@18.3.1__react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next-themes/dist/index.js:1:335)
    at exports.ThemeProvider (webpack-internal:///./node_modules/.pnpm/next-themes@0.2.1_next@13.5.6_react-dom@18.3.1_react@18.3.1__react@18.3.1__react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next-themes/dist/index.js:1:3636)
    at ConfigProvider (webpack-internal:///./node_modules/.pnpm/nextra-theme-docs@2.13.4_next@13.5.6_react-dom@18.3.1_react@18.3.1__react@18.3.1__nextra@2.13_k2lwaadcjqvucsrfzrlpwgtlbq/node_modules/nextra-theme-docs/dist/index.js:258:3)
    at Layout (webpack-internal:///./node_modules/.pnpm/nextra-theme-docs@2.13.4_next@13.5.6_react-dom@18.3.1_react@18.3.1__react@18.3.1__nextra@2.13_k2lwaadcjqvucsrfzrlpwgtlbq/node_modules/nextra-theme-docs/dist/index.js:3084:5)
    at Nextra (webpack-internal:///./node_modules/.pnpm/nextra@2.13.4_next@13.5.6_react-dom@18.3.1_react@18.3.1__react@18.3.1__react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/nextra/dist/layout.js:14:3)
    at App (webpack-internal:///./pages/_app.mdx:22:34)
    at MDXContent
    at StyleRegistry (/Users/joe/Files/development/forus-labs/forui/docs/node_modules/.pnpm/styled-jsx@5.1.1_react@18.3.1/node_modules/styled-jsx/dist/index/index.js:449:36)
    at ek (/Users/joe/Files/development/forus-labs/forui/docs/node_modules/.pnpm/next@13.5.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:30:13126)
    at eY (/Users/joe/Files/development/forus-labs/forui/docs/node_modules/.pnpm/next@13.5.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:39:1766)
    at eV (/Users/joe/Files/development/forus-labs/forui/docs/node_modules/.pnpm/next@13.5.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:39:3110)
    at div
    at e1 (/Users/joe/Files/development/forus-labs/forui/docs/node_modules/.pnpm/next@13.5.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:48:761)

```

### Related

- https://github.com/shuding/nextra/issues/2869

**Comment by Pante** [comment]
@kawaijoe is this still relevant?

**Comment by kawaijoe** [comment]
I believed it is fixed in the recent update.
